config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:index, :show]

  root "pages#index"
      
  get '/index', to: "pages#index"

  get '/contacts', to: "pages#contact"

  resources :recipes

  resources :posts

  resources :categories, only: [:new, :create, :show]

  # TheComments routes
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	include TheComments::Commentable

	belongs_to :user
	#has_many :comments
	has_many 	:ingredients
	has_many :recipe_categories
	has_many :categories, through: :recipe_categories
	validates :user_id, presence: true
	validates :title, presence: true, length: {minimum: 5, maximum: 100}
	#validates :summary, presence: true, length: {minimum: 10, maximum: 150}
	validates :description, presence: true, length: {minimum: 20, maximum: 3500}

	accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true
	# accepts_nested_attributes_for :ingredients,
	# 															reject_if: proc { |attributes| attributes['quantity'].blank? },
	# 															allow_destroy: true										

	has_attached_file :recipe_image, styles: { large: "570x427#", medium: "270x203#" }
	validates_attachment_content_type :recipe_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	# Denormalization methods
  # Check the documentation for information on advanced usage
  def commentable_title
    "Undefined Post Title"
  end

  def commentable_url
    "#"
  end

  def commentable_state
    "published"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@recipe = Recipe.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
	end

	def show
		@recipe = Recipe.find(params[:id])
		@comments = @recipe.comments.with_state([:draft, :published])

		#@category = Category.find(params[:id])

		@random_recipe = Recipe.where.not(id: @recipe).order("RANDOM()").first
	end

	def new
		@recipe = Recipe.new
	end

	def create
		#@recipe = Recipe.new(recipe_params)
		#@chef = Chef.find(1)

		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Новый рецепт создан успешно."
		else
			render 'new'
		end
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			redirect_to recipe_path(@recipe), notice: "Ваш рецепт обновлен успешно!"
		else
			render 'edit'
		end
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :summary, :description, :difficulty, :pre_time, :cook_time, :servers, :recipe_image, :user_id, ingredients_attributes: [:id, :name, :quantity, :_destroy], category_ids: [])
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_category_menu.html.erb
<div class="widget">
  <ul class="categories right">
    <% if current_page?(recipes_path) %>
      <li class="active"><%= link_to "Все рецепты", recipes_path %></li>
    <% else %>
      <li><%= link_to "Все рецепты", recipes_path %></li>
    <% end %>
      <% Category.all.each do |category| %>
        <li><%= link_to_in_li category.name, category_path(category) %></li>
      <% end %>
      <li><a href="#">Видео рецепты</a></li>
  </ul>
</div>

app/views/recipes/_form.html.erb
<div class="submit_recipe container">
	<%= form_for(@recipe, html: { multipart: true }) do |f| %>
		<section>
			<h2>Основное</h2>
			<p>Все поля являются обязательными.</p>
			<div class="f-row">
				<div class="full">
					<%= f.text_field :title, :placeholder => "Название рецепта" %>
				</div>
			</div>
			<div class="f-row">
				<div class="third"><%= f.text_field :pre_time, :placeholder => "Время подготовления" %></div>
				<div class="third"><%= f.text_field :cook_time, :placeholder => "Время приготовления" %></div>
				<div class="third"><%= f.text_field :difficulty, :placeholder => "Сложность" %></div>
			</div>
			<div class="f-row">
				<div class="third"><%= f.text_field :servers, :placeholder => "На сколько людей серверовано?" %></div>
				<div class="third">
					
				</div>
				
			</div>
		</section>
		<section>
			<h2>Описание</h2>
			<div class="f-row">
				<div class="full">
				<%= f.text_area :summary, :placeholder => "Введите короткое описание", :class => 'ckeditor' %>
				</div>
			</div>
		</section>

		<section>
			<h2>Ингредиенты</h2>
			<%= f.fields_for :ingredients do |ing| %>
				<%= render 'ingredient_fields', f: ing %>
			<% end %>
				<div class="f-row full">
					<%= link_to_add_association 'Добавить ингредиент', f, :ingredients, class: "button" %>
				</div>
		</section>

		<section>
			<h2>Сам рецепт</h2>
			<div class="f-row">
				<%= f.text_area :description, :placeholder => "Введите сам рецепт", :class => 'ckeditor' %>
			</div>
		</section>

		<section>
			<h2>Фото рецепта</h2>
			<div class="f-row full">
				<%= f.file_field :recipe_image %>
			</div>
		</section>

		<div class="f-row full">
			<%= f.submit(@recipe.new_record? ? 'Создать рецепт' : 'Отредактировать рецепт', class: "button", :id => "submitRecipe") %>
		</div>
	<% end %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="form-group f-row ingredient">
    <div class="large"><%= f.text_field :name, :placeholder => "Ингредиент" %></div>
    <div class="small"><%= f.text_field :quantity, :placeholder => "Количество" %></div>
		<!-- <div class="third"><select><option selected="selected">Выбирете категорию</option></select></div> -->
  
    <%= link_to_remove_association "-", f, class: "remove button" %>
  </div>
</div>

app/views/recipes/_slide_recipe.html.erb
<div class="entries row">
	<% obj.each do |recipe| %>
		<div class="entry one-third wow fadeInLeft" data-wow-delay="<%= cycle(".2s", ".4s", ".8s") %>">
			<figure>
				<%= image_tag recipe.recipe_image.url(:medium) %>
				<figcaption>
					<%= link_to recipe_path(recipe) do %>
						<i class="ico i-view"></i> <span>Просмотреть рецепт</span>
					<% end %>
				</figcaption>
			</figure>
			<div class="container">
				<h2><%= link_to recipe_path(recipe) do %><%= recipe.title %><% end %></h2>
				<div class="actions">
					<div>
						<div class="difficulty"><i class="ico i-medium"></i><a href="#"><%= recipe.difficulty %></a></div>
						<div class="likes"><i class="ico i-likes"></i><a href="#">10</a></div>
						<div class="comments"><i class="ico i-comments"></i><a href="recipe.html#comments">7</a></div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/recipes/edit.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		<!--row-->
		<div class="row">
			<header class="s-title">
				<h1>Редактор рецепта</h1>
			</header>
			<!--content-->
			<section class="content full-width wow fadeInUp">
				<%= render 'form' %>
			</section>
			<!--//content-->
		</div>
		<!--//row-->
	</div>
	<!--//wrap-->
</main>
<!--//main-->

app/views/recipes/index.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		<!--row-->
		<div class="row">
			<header class="s-title wow fadeInLeft">
				<h1>Рецепты</h1>
			</header>
			
			<!--content-->
			<section class="content three-fourth wow fadeInUp">
				<%= render 'slide_recipe', obj: @recipe %>
			</section>
			
			<!--right sidebar-->
			<aside class="sidebar one-fourth wow fadeInRight">
				<%= render 'category_menu' %>
				<div class="widget">
					<h3>Реклама</h3>
					<a href="#"><%= image_tag("advertisment.jpg") %></a>
				</div>
			</aside>
			<!--//right sidebar-->
		</div>
		<!--//row-->
		
		<div class="paginate wow fadeInUp">
			<%= will_paginate @recipe %>
		</div>

	</div>
	<!--//wrap-->
	
</main>
<!--//main-->

app/views/recipes/new.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		<!--row-->
		<div class="row">
			<header class="s-title">
				<h1>Добавить новый рецепт</h1>
			</header>
			<!--content-->
			<section class="content full-width wow fadeInUp">
				<%= render 'form' %>
			</section>
			<!--//content-->
		</div>
		<!--//row-->
	</div>
	<!--//wrap-->
</main>
<!--//main-->

app/views/recipes/show.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		
		<!--row-->
		<div class="row">
			<header class="s-title wow fadeInLeft">
				<h1><%= @recipe.title %></h1>
			</header>
			<!--content-->
			<section class="content three-fourth">
				<div class="row">
				<!--recipe-->
					<div class="recipe">
						<!--two-third-->
						<article class="two-third wow fadeInLeft">
							<div class="image">
								<%= link_to '' do %>
									<%= image_tag @recipe.recipe_image.url(:large) %>
								<% end %>
							</div>
							<div class="intro"><p><%= @recipe.summary %></p></div>
							<div class="instructions">
								<ol>
									<li><%= @recipe.description %></li>
								</ol>
							</div>
						</article>
						<!--//two-third-->
						
						<!--one-third-->
						<article class="one-third wow fadeInDown">
							<dl class="basic">
								<dt>Время подготовления</dt>
								<dd><%= @recipe.pre_time %></dd>
								<dt>Время приготовления</dt>
								<dd><%= @recipe.cook_time %></dd>
								<dt>Сложность</dt>
								<dd><%= @recipe.difficulty %></dd>
								<dt>Серверовка</dt>
								<dd><%= @recipe.servers %></dd>
							</dl>
							
							<dl class="user">
								<dt>Категория</dt>
                <% if @recipe.categories.any? %>
                  <dd><%= render @recipe.categories %></dd>
                <% else %>
                  <dd>Не указана</dd>
                <% end %>
								<dt>Автор</dt>
								<dd><%= link_to "#{@recipe.user.chefname}", user_path(@recipe.user) %></dd>
							</dl>
							
							<dl class="ingredients">
								<% @recipe.ingredients.each do |ing| %>
									<dt><%= ing.quantity %></dt>
									<dd><%= ing.name %></dd>
								<% end %>
							</dl>
						</article>
						<!--//one-third-->
					</div>
					<!--//recipe-->
					<%= render partial: 'the_comments/tree', locals: { commentable: @recipe, comments_tree: @comments } %>
				</div>
			</section>
			<!--//content-->

			<!--right sidebar-->
				<aside class="sidebar one-fourth wow fadeInRight">
					<div class="widget nutrition entry">
						<h3>Не хотите приготовить?</h3>
						<figure>
							<%= image_tag @random_recipe.recipe_image.url(:medium) %>
							<figcaption>
								<%= link_to recipe_path(@random_recipe) do %>
									<i class="ico i-view"></i> <span>Просмотреть рецепт</span>
								<% end %>
							</figcaption>
						</figure>
						<div class="random_recipe">
							<h2><%= link_to recipe_path(@random_recipe) do %><%= @random_recipe.title %><% end %></h2>
							<div class="random_actions">
								<ul>
									<li><i class="ico i-medium"></i><a href="#"><%= @random_recipe.difficulty %></a></li>
									<li><i class="ico i-likes"></i><a href="#">10</a></li>
									<li><i class="ico i-comments"></i><a href="recipe.html#comments">7</a></li>
								</ul>
							</div>
						</div>
					</div>
					
					<div class="widget share">
						<ul class="boxed">
							<li class="light"><a href="#" title="Facebook"><i class="ico i-facebook"></i> <span>Share on Facebook</span></a></li>
							<li class="medium"><a href="#" title="Twitter"><i class="ico i-twitter"></i> <span>Share on Twitter</span></a></li>
							<li class="dark"><a href="#" title="Favourites"><i class="ico i-favourites"></i> <span>Add to Favourites</span></a></li>
						</ul>
					</div>
					
					<!-- <div class="widget members">
						<h3>Members who liked this recipe</h3>
						<ul class="boxed">
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar1.jpg" alt="" /><span>Kimberly C.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar2.jpg" alt="" /><span>Alex J.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar3.jpg" alt="" /><span>Denise M.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar9.jpg" alt="" /><span>Jason H.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar8.jpg" alt="" /><span>Jennifer W.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar4.jpg" alt="" /><span>Anabelle Q.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar7.jpg" alt="" /><span>Thomas M.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar5.jpg" alt="" /><span>Michelle S.</span></a></div></li>
							<li><div class="avatar"><a href="my_profile.html"><img src="images/avatar6.jpg" alt="" /><span>Bryan A.</span></a></div></li>
						</ul>
					</div> -->
				</aside>
				<!--//right sidebar-->
		
		</div>
		<!--//row-->
	</div>
	<!--//wrap-->
</main>
<!--//main-->