config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:index, :show]

  root "pages#index"
      
  get '/index', to: "pages#index"

  get '/contacts', to: "pages#contact"

  resources :recipes

  resources :posts

  resources :categories, only: [:new, :create, :show]

  # TheComments routes
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 2, maximum: 25 }
	has_many :recipe_categories
	has_many :recipes, through: :recipe_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def new
    @category = Category.new
  end

  def create
    #binding.pry
    @category = Category.new(style_params)
    if @category.save
      redirect_to recipes_path, notice: "Категория создана успешно"
    else
      render 'new'
    end
  end

  private

  def style_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span class="quiet"><%= link_to category.name, category_path(category) %> </span>

app/views/categories/_form.html.erb
<div class="modal container">
	<%= form_for(@category, html: { multipart: true }) do |f| %>
		<h3>Добавить категорию</h3>
		<div id="message" class="alert alert-danger"></div>
		<div class="f-row">
			<%= f.text_field :name, :placeholder => "Название категории" %>
		</div>
		
		<div class="f-row bwrap">
			<%= f.submit(@category.new_record? ? 'Создать категорию' : 'Отредактировать категорию', class: "button", :id => "submitRecipe") %>
		</div>
	<% end %>
</div>

app/views/categories/new.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		<!--row-->
		<div class="row">
			<header class="s-title">
				<h1>Добавить новую категорию</h1>
			</header>
			<!--content-->
			<section class="content center full-width wow fadeInUp">
				<%= render 'form' %>
			</section>
			<!--//content-->
		</div>
		<!--//row-->
	</div>
	<!--//wrap-->
</main>
<!--//main-->

app/views/categories/show.html.erb
<!--main-->
<main class="main" role="main">
	<!--wrap-->
	<div class="wrap clearfix">
		<!--row-->
		<div class="row">
			<header class="s-title wow fadeInLeft">
				<h1><%= @category.name %></h1>
			</header>
			
			<!--content-->
			<section class="content three-fourth wow fadeInUp">
			<% @recipes.each_slice(3) do |recipes| %>
				<div class="entries row">
					<% recipes.each do |recipe| %>
						<div class="entry one-third wow fadeInLeft">
							<figure>
								<%= image_tag recipe.recipe_image.url(:medium) %>
								<figcaption>
									<%= link_to recipe_path(recipe) do %>
										<i class="ico i-view"></i> <span>Просмотреть рецепт</span>
									<% end %>
								</figcaption>
							</figure>
							<div class="container">
								<h2><%= link_to recipe_path(recipe) do %><%= recipe.name %><% end %></h2>
								<div class="actions">
									<div>
										<div class="difficulty"><i class="ico i-medium"></i><a href="#"><%= recipe.difficulty %></a></div>
										<div class="likes"><i class="ico i-likes"></i><a href="#">10</a></div>
										<div class="comments"><i class="ico i-comments"></i><a href="recipe.html#comments">7</a></div>
									</div>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
			</section>
			
			<!--right sidebar-->
			<aside class="sidebar one-fourth wow fadeInRight">
				<div class="widget">
					<ul class="categories right">
						<li class="active"><a href="#">All recipes</a></li>
						<li><a href="#">Apetizers</a></li>
						<li><a href="#">Cocktails</a></li>
						<li><a href="#">Deserts</a></li>
						<li><a href="#">Eggs</a></li>
						<li><a href="#">Equipment</a></li>
						<li><a href="#">Events</a></li>
						<li><a href="#">Fish</a></li>
						<li><a href="#">Fitness</a></li>
						<li><a href="#">Healthy</a></li>
						<li><a href="#">Asian</a></li>
						<li><a href="#">Mexican</a></li>
						<li><a href="#">Pizza</a></li>
						<li><a href="#">Kids</a></li>
						<li><a href="#">Meat</a></li>
						<li><a href="#">Snacks</a></li>
						<li><a href="#">Salads</a></li>
						<li><a href="#">Storage</a></li>
						<li><a href="#">Vegetarian</a></li>
					</ul>
				</div>
				<div class="widget">
					<h3>Advertisment</h3>
					<a href="#"><%= image_tag("advertisment.jpg") %></a>
				</div>
			</aside>
			<!--//right sidebar-->
		</div>
		<!--//row-->
	</div>
	<!--//wrap-->
</main>
<!--//main-->