config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:index, :show]

  root "pages#index"
      
  get '/index', to: "pages#index"

  get '/contacts', to: "pages#contact"

  resources :recipes

  resources :posts

  resources :categories, only: [:new, :create, :show]

  # TheComments routes
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]
end

app/views/layouts/_footer.html.erb
<!--footer-->
<footer class="foot" role="contentinfo">
	<div class="wrap clearfix">
		<div class="row">
			<article class="one-half">
				<h5>О нас</h5>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci.</p>
			</article>
			<article class="one-fourth">
				<h5>Нужна помощь?</h5>
				<p>Contact us via phone or email</p>
				<p><em>T:</em>  +1 555 555 555<br /><em>E:</em>  <a href="#">socialuser@email.com</a></p>
			</article>
			<article class="one-fourth">
				<h5>Присоединяйтесь</h5>
				<ul class="social">
					<li class="facebook"><a href="#" title="facebook">facebook</a></li>
					<li class="youtube"><a href="#" title="youtube">youtube</a></li>
					<li class="rss"><a href="#" title="rss">rss</a></li>
					<li class="gplus"><a href="#" title="gplus">google plus</a></li>
					<li class="linkedin"><a href="#" title="linkedin">linkedin</a></li>
					<li class="twitter"><a href="#" title="twitter">twitter</a></li>
					<li class="pinterest"><a href="#" title="pinterest">pinterest</a></li>
					<li class="vimeo"><a href="#" title="vimeo">vimeo</a></li>
				</ul>
			</article>
			
			<div class="bottom">
				<p class="copy">Copyright 2016 Socialuser. Все права защищены</p>
				
				<nav class="foot-nav">
					<ul>
						<li><%= link_to 'Главная', root_path, :title => "Главная" %></li>
						<li><a href="recipes.html" title="Recipes">Рецепты</a></li>
						<li><a href="blog.html" title="Blog">Статьи</a></li>
						<li><a href="contact.html" title="Contact">Контакты</a></li>    
						<li><a href="find_recipe.html" title="Search for recipes">Поиск рецептов</a></li>
						<li><%= link_to 'Войти', new_user_session_path, :title => "Войти" %></li>	
						<li><%= link_to 'Регистрация', new_user_registration_path, :title => "Регистрация" %></li>												
					</ul>
				</nav>
			</div>
		</div>
	</div>
</footer>
<!--//footer-->

app/views/layouts/_header.html.erb
<header class="head" role="banner">
	<!--wrap-->
	<div class="wrap clearfix">
	<%= link_to root_path, class: "logo" do %>
		<%= image_tag("ico/logo.png") %>
	<% end %>
		
		<nav class="main-nav" role="navigation" id="menu">
			<ul>
				<% if current_page?(root_path) %>
					<li class="current-menu-item">
				<% else %>
					<li>
				<% end %>
					<%= link_to root_path, :title => "Главная" do %>
						<span>Главная</span>
					<% end %>
				</li>
				<% if current_page?(recipes_path) %>
					<li class="current-menu-item">
				<% else %>
					<li>
				<% end %>
					<%= link_to recipes_path, :title => "Рецепты" do %>
						<span>Рецепты</span>
					<% end %>
				</li>
				<li>
					<%= link_to posts_path, :title => "Статьи" do %>
						<span>Статьи</span>
					<% end %>
				</li>
				<li><a href="#" title="Pages"><span>Едим глазами</span></a>
					<ul>
						<li><a href="left_sidebar.html" title="Left sidebar page">Left sidebar page</a></li>
						<li><a href="right_sidebar.html" title="Right sidebar page">Right sidebar page</a></li>
						<li><a href="two_sidebars.html" title="Both sidebars page">Both sidebars page</a></li>
						<li><a href="full_width.html" title="Full width page">Full width page</a></li>
						<li><a href="login.html" title="Login page">Login page</a></li><li><a href="register.html" title="Register page">Register page</a></li>
						<li><a href="error404.html" title="Error page">Error page</a></li>
					</ul>
				</li>
				<li>
					<%= link_to contacts_path, :title => "Контакты" do %>
						<span>Контакты</span>
					<% end %>
				</li>
			</ul>
		</nav>
		
		<nav class="user-nav" role="navigation">
			<ul>
				<li class="light"><a href="find_recipe.html" title="Поиск рецептов"><i class="ico i-search"></i> <span>Поиск рецептов</span></a></li>
				<li class="medium">
					<% if user_signed_in? %>
						<%= link_to user_path(current_user), title: "Мой аккаунт" do %>
							<i class="ico i-account"></i> <span>Мой аккаунт</span>
						<% end %>
					<% else %>
						<%= link_to new_user_session_path, title: "Войти в аккаунт" do %>
							<i class="ico i-account"></i> <span>Войти в аккаунт</span>
						<% end %>
					<% end %>
				</li>
				<li class="dark">
				<%= link_to new_recipe_path, title: "Добавить рецепт" do %>
					<i class="ico i-submitrecipe"></i>
					<span>Добавить рецепт</span>
				<% end %>
				</li>
				<% if user_signed_in? %>
					<li class="medium">
						<%= link_to new_post_path, title: "Добавить статью" do %>
						<i class="ico i-wrote_post"></i>
						<span>Добавить статью</span>
						<% end %>
					</li>
				<% end %>
			</ul>
		</nav>
	</div>
	<!--//wrap-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KopilkaReceptov</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>

  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<% if alert %>
	<div id="notice_wrapper">
		<p class="alert"><%= alert %></p>	
	</div>
	<% elsif notice %>
		<div id="notice_wrapper">
			<p class="notice"><%= notice %></p>		
		</div>
	<% end %>

<%= yield %>
	
	<%= render 'layouts/footer' %>

<!-- 	<div class="preloader">
		<div class="spinner"></div>
	</div> -->

<%= javascript_include_tag "script" %>
<%= javascript_include_tag "jquery.uniform.min" %>
<%= javascript_include_tag "wow" %>
</body>
</html>

<script>
	window.dynamicNumbersBound = false;
	var wow = new WOW();
	WOW.prototype.show = function(box) {
		wow.applyStyle(box);
		if (typeof box.parentNode !== 'undefined' && hasClass(box.parentNode, 'dynamic-numbers') && !window.dynamicNumbersBound) {
			bindDynamicNumbers();
			window.dynamicNumbersBound = true;
		}
		return box.className = "" + box.className + " " + wow.config.animateClass;
	};
	wow.init();
	
	function hasClass(element, cls) {
		return (' ' + element.className + ' ').indexOf(' ' + cls + ' ') > -1;
	}
	
	function bindDynamicNumbers() {
		$('.dynamic-number').each(function() {				
			var startNumber = $(this).text();
			var endNumber = $(this).data('dnumber');
			var dynamicNumberControl = $(this);
			
			$({numberValue: startNumber}).animate({numberValue: endNumber}, {
				duration: 4000,
				easing: 'swing',
				step: function() { 
					$(dynamicNumberControl).text(Math.ceil(this.numberValue)); 
				}
			});
		});	
	}
	
</script>


<script>
	$(document).ready(function() {
		setTimeout(function() {
			$('#notice_wrapper').fadeOut("slow", function() {
				$this.remove();
			});
		}, 3500 );
	});
</script>